# Numpy

## Escalares

In [1]:
import numpy as np

s = np.array(7)
s.shape

()

In [4]:
x = s + 1
x

8

In [5]:
type(x)

numpy.int32

## Vectores

In [6]:
v = np.array([3, 6, 9])
v.shape


(3,)

In [7]:
type(v)

numpy.ndarray

In [26]:
x = np.array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [29]:
x[x % 4 == 0]

array([0, 4, 8])

In [9]:
x = np.array([[[1],[2],[3]], [[4],[5],[6]]])
x.shape

(2, 3, 1)

In [12]:
x[1:2]

array([[[4],
        [5],
        [6]]])

In [17]:
x = np.array([[ 0,  1,  2],
...            [ 3,  4,  5],
...            [ 6,  7,  8],
...            [ 9, 10, 11]])

In [18]:
x[1:2, 1:3]

array([[4, 5]])

In [19]:
x[1:2, [1, 2]]

array([[4, 5]])

In [33]:
v = np.array([1,2,3,4])
v

array([1, 2, 3, 4])

In [38]:
x = v.reshape(1,4)
x

array([[1, 2, 3, 4]])